version: "3.9"
services:
  clothing-model:
    image: zoomcamp_10_model:xception_v4
  gateway:
    image: zoomcamp_10_gateway:003
    environment:
      - TF-SERVING=clothing-model:8500
    ports:
      - "9696:9696"